
name: 'Standard Ruby'
description: 'A GitHub Action that lints your Ruby code with Standard Ruby'
author: 'Justin Searls <searls@gmail.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
env:
  GITHUB_TOKEN: secrets.GITHUB_TOKEN
branding:
  icon: 'code'
  color: 'gray-dark'
